create table COUNTRIES(
ID int primary key,
COUNTRY varchar(50));

CREATE TABLE CITIES(
ID int primary key ,
COUNTRYID int not null,
CITY varchar(50),
foreign key (COUNTRYID) REFERENCES COUNTRIES(ID)) ;

create table TOWNS(
ID int primary key ,
CITYID int not null,
TOWN varchar(50),
FOREIGN KEY (CITYID) REFERENCES CITIES(ID));

Create table DISTRICTS(
ID int primary key,
TOWNID int not null ,
DISTRICT varchar(50),
FOREIGN KEY (TOWNID) REFERENCES TOWNS(ID));

create table USERS(
ID int primary key ,
USERNAME_ varchar(50),
PASSWORD_ varchar(50),
NAMESURNAME varchar(50),
EMAIL varchar(50),
GENDER char(1),
BIRTHDATE date,
CREATEDATE DATETIME,
TELNR1 varchar (20),
TELNR2 varchar (20));

CREATE TABLE ADDRESS(
ID int primary key ,
USERID int not null,
COUNTRYID int not null,
CITYID int not null,
TOWNID int not null,
DISTRICTID int not null,
POSTALCODE varchar(50),
ADDRESSTEXT VARCHAR(100),
FOREIGN KEY (USERID) REFERENCES USERS(ID),
FOREIGN KEY (COUNTRYID) REFERENCES COUNTRIES(ID),
FOREIGN KEY (CITYID) REFERENCES CITIES(ID),
FOREIGN KEY (TOWNID) REFERENCES TOWNS(ID),
FOREIGN KEY (DISTRICTID) REFERENCES DISTRICTS(ID));

CREATE TABLE ITEMS(
ID int primary key ,
ITEMCODE varchar(50),
ITEMNAME varchar(50),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
BRAND VARCHAR(50));

CREATE TABLE ORDERS(
ID int primary key,
USERID int not null,
DATE_ date,
TOTALPRICE float,
STATUS_ VARCHAR(50),
ADDRESSID int not null,
FOREIGN KEY (USERID) REFERENCES USERS(ID),
FOREIGN KEY (ADDRESSID) references ADDRESS(ID));

CREATE TABLE ORDERDETAILS(
ID int primary key ,
ORDERID int not null,
ITEMID int not null,
AMOUNT int not null,
UNITPRICE FLOAT ,
LINETOTAL FLOAT,
FOREIGN KEY (ORDERID) REFERENCES ORDERS(ID),
FOREIGN KEY (ITEMID) REFERENCES ITEMS(ID));

CREATE TABLE INVOICES(
ID int primary key ,
ORDERID int not null,
DATE_ DATE,
ADDRESSID int ,
CARGOFICHENO VARCHAR(50),
TOTALPRICE FLOAT,
FOREIGN KEY (ORDERID) REFERENCES ORDERS(ID),
FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS(ID));

CREATE TABLE INVOICEDETAILS(
ID int primary key ,
INVOICEID int not null ,
ORDERDETAILID int not null ,
ITEMID int not null,
AMOUNT INT ,
UNITPRICE FLOAT ,
LINETOTAL FLOAT ,
FOREIGN KEY (INVOICEID) REFERENCES INVOICES(ID),
FOREIGN KEY (ORDERDETAILID) REFERENCES ORDERDETAILS(ID),
FOREIGN KEY (ITEMID) REFERENCES ITEMS(ID));

CREATE TABLE PAYMENTS(
ID int primary key ,
ORDERID int not null ,
PAYMENTTYPE VARCHAR(50),
DATE_ DATE,
ISOK bit,
APPROVECODE VARCHAR(50),
PAYMENTTOTAL float,
FOREIGN KEY (ORDERID) REFERENCES ORDERS(ID));

